# SNAKE CONFIG
SNAKE_COLOR = "white"
SNAKE_INITIAL_SIZE = 3
SNAKE_SPEED = "fastest"
SNAKE_SHAPE = "square"
SNAKE_SEGMENT_SIZE = 20

# SCREEN CONFIG
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"
SLEEP_TIME = 0.1

# FOOD CONFIG
FOOD_SHAPE = "square"
FOOD_SIZE = 20
FOOD_COLOR = "yellow"
FOOD_SPEED = "fastest"

# INTERACTIONS
COLLISION_ERROR = 1

# SCOREBOARD CONFIGS
SCOREBOARD_SPEED = "fastest"
SCOREBOARD_DISTANCE_TO_CENTER = 0
SCOREBOARD_DISTANCE_TO_TOP = 60
SCOREBOARD_X_POSITION = 0 - SCOREBOARD_DISTANCE_TO_CENTER
SCOREBOARD_Y_POSITION = SCREEN_HEIGHT / 2 - SCOREBOARD_DISTANCE_TO_TOP
SCOREBOARD_TEXT_COLOR = "white"
SCOREBOARD_TEXT_ARG = "SCORE: "
SCOREBOARD_TEXT_ALIGN = "center"
SCOREBOARD_TEXT_FONT = "Console"
SCOREBOARD_TEXT_SIZE = 24
SCOREBOARD_TEXT_STYLE = "normal"
SCOREBOARD_TEXT_TUPLE = (SCOREBOARD_TEXT_FONT, SCOREBOARD_TEXT_SIZE, SCOREBOARD_TEXT_STYLE)
SCOREBOARD_GAME_OVER_TEXT = "GAME OVER"
SCOREBOARD_GAME_OVER_TEXT_SIZE = 30
SCOREBOARD_GAME_OVER_TEXT_TUPLE = (SCOREBOARD_TEXT_FONT, SCOREBOARD_GAME_OVER_TEXT_SIZE, SCOREBOARD_TEXT_STYLE)
